/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RechnerSlugRouteImport } from './routes/rechner.$slug'
import { Route as KategorieSlugRouteImport } from './routes/kategorie.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnerSlugRoute = RechnerSlugRouteImport.update({
  id: '/rechner/$slug',
  path: '/rechner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorieSlugRoute = KategorieSlugRouteImport.update({
  id: '/kategorie/$slug',
  path: '/kategorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/rechner/$slug': typeof RechnerSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/rechner/$slug': typeof RechnerSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/rechner/$slug': typeof RechnerSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/kategorie/$slug'
    | '/rechner/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/kategorie/$slug'
    | '/rechner/$slug'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/kategorie/$slug'
    | '/rechner/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KategorieSlugRoute: typeof KategorieSlugRoute
  RechnerSlugRoute: typeof RechnerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechner/$slug': {
      id: '/rechner/$slug'
      path: '/rechner/$slug'
      fullPath: '/rechner/$slug'
      preLoaderRoute: typeof RechnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorie/$slug': {
      id: '/kategorie/$slug'
      path: '/kategorie/$slug'
      fullPath: '/kategorie/$slug'
      preLoaderRoute: typeof KategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KategorieSlugRoute: KategorieSlugRoute,
  RechnerSlugRoute: RechnerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
